/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DoneRouteImport } from './routes/done'
import { Route as BuildQueueRouteImport } from './routes/build-queue'
import { Route as BuildCyclesRouteImport } from './routes/build-cycles'
import { Route as BacklogRouteImport } from './routes/backlog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecsIdRouteImport } from './routes/specs.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneRoute = DoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildQueueRoute = BuildQueueRouteImport.update({
  id: '/build-queue',
  path: '/build-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildCyclesRoute = BuildCyclesRouteImport.update({
  id: '/build-cycles',
  path: '/build-cycles',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRoute = BacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsIdRoute = SpecsIdRouteImport.update({
  id: '/specs/$id',
  path: '/specs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRoute
  '/build-cycles': typeof BuildCyclesRoute
  '/build-queue': typeof BuildQueueRoute
  '/dashboard': typeof DashboardRoute
  '/done': typeof DoneRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/specs/$id': typeof SpecsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRoute
  '/build-cycles': typeof BuildCyclesRoute
  '/build-queue': typeof BuildQueueRoute
  '/dashboard': typeof DashboardRoute
  '/done': typeof DoneRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/specs/$id': typeof SpecsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRoute
  '/build-cycles': typeof BuildCyclesRoute
  '/build-queue': typeof BuildQueueRoute
  '/dashboard': typeof DashboardRoute
  '/done': typeof DoneRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/specs/$id': typeof SpecsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backlog'
    | '/build-cycles'
    | '/build-queue'
    | '/dashboard'
    | '/done'
    | '/home'
    | '/login'
    | '/preview'
    | '/roadmap'
    | '/settings'
    | '/specs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backlog'
    | '/build-cycles'
    | '/build-queue'
    | '/dashboard'
    | '/done'
    | '/home'
    | '/login'
    | '/preview'
    | '/roadmap'
    | '/settings'
    | '/specs/$id'
  id:
    | '__root__'
    | '/'
    | '/backlog'
    | '/build-cycles'
    | '/build-queue'
    | '/dashboard'
    | '/done'
    | '/home'
    | '/login'
    | '/preview'
    | '/roadmap'
    | '/settings'
    | '/specs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacklogRoute: typeof BacklogRoute
  BuildCyclesRoute: typeof BuildCyclesRoute
  BuildQueueRoute: typeof BuildQueueRoute
  DashboardRoute: typeof DashboardRoute
  DoneRoute: typeof DoneRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PreviewRoute: typeof PreviewRoute
  RoadmapRoute: typeof RoadmapRoute
  SettingsRoute: typeof SettingsRoute
  SpecsIdRoute: typeof SpecsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/done': {
      id: '/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof DoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-queue': {
      id: '/build-queue'
      path: '/build-queue'
      fullPath: '/build-queue'
      preLoaderRoute: typeof BuildQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-cycles': {
      id: '/build-cycles'
      path: '/build-cycles'
      fullPath: '/build-cycles'
      preLoaderRoute: typeof BuildCyclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs/$id': {
      id: '/specs/$id'
      path: '/specs/$id'
      fullPath: '/specs/$id'
      preLoaderRoute: typeof SpecsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacklogRoute: BacklogRoute,
  BuildCyclesRoute: BuildCyclesRoute,
  BuildQueueRoute: BuildQueueRoute,
  DashboardRoute: DashboardRoute,
  DoneRoute: DoneRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PreviewRoute: PreviewRoute,
  RoadmapRoute: RoadmapRoute,
  SettingsRoute: SettingsRoute,
  SpecsIdRoute: SpecsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
