import type { User, Milestone, BuildCycle, Spec, Comment, Activity, DemoState } from "@/types/demo";

export const projects = [
  { id: "launchos", name: "LaunchOS" },
  { id: "talelingo", name: "TaleLingo" },
  { id: "corelynext", name: "CorelyNext" },
];

export const users: User[] = [
  { id: "u-ha", name: "Ha", role: "Founder", avatar: "H", type: "admin" },
  { id: "u-anna", name: "Anna", role: "Stakeholder", avatar: "A", type: "stakeholder" },
  { id: "u-david", name: "David", role: "Developer", avatar: "D", type: "developer" },
  { id: "u-linh", name: "Linh", role: "Designer", avatar: "L", type: "stakeholder" },
];

export const milestones: Milestone[] = [
  { id: "mvp", name: "MVP", targetDate: "2026-07-05" },
  { id: "beta", name: "Private Beta", targetDate: "2026-07-20" },
  { id: "v1", name: "v1 Launch", targetDate: "2026-08-15" },
];

export const buildCycles: BuildCycle[] = [
  {
    id: "cycle-mvp-week-1",
    name: "MVP Build Week 1",
    goal: "Ship team invite, asset library, and waitlist improvements",
    startDate: "2026-06-29",
    endDate: "2026-07-05",
    status: "active",
    specIds: ["REQ-002", "REQ-003", "REQ-001"],
  },
  {
    id: "cycle-beta-week-1",
    name: "Beta Build Week 1",
    goal: "Prepare audience import and billing limits",
    startDate: "2026-07-06",
    endDate: "2026-07-12",
    status: "planned",
    specIds: ["REQ-004", "REQ-006"],
  },
];

export const specs: Spec[] = [
  {
    id: "REQ-001",
    title: "Waitlist Signup",
    status: "done",
    priority: "medium",
    roadmapLane: "Now",
    milestoneId: "mvp",
    ownerId: "u-ha",
    assigneeId: "u-david",
    summary: "Visitors can join the waitlist from the landing page using only their email address.",
    problem: "We need to capture early interest before launching the product.",
    expectedBehavior: "Email signup form with validation and confirmation message.",
    acceptanceCriteria: [
      "Email field appears in hero section.",
      "Invalid email shows validation error.",
      "Successful signup shows confirmation message.",
      "Email is stored for later export.",
    ],
    outOfScope: ["Admin list", "Email automation"],
    decisions: [
      { id: "d1", text: "Use single-field email form, no name required." },
      { id: "d2", text: "Store emails in waitlist table for CSV export." },
    ],
    previewUrl: "https://preview.launchos.dev/waitlist",
    prUrl: "https://github.com/acme/launchos/pull/142",
    releaseNotes:
      "Added a simple waitlist signup form to the landing page with email validation and success confirmation.",
    gitSyncedAt: "2026-06-22",
    approvedAt: "2026-06-20",
    updatedAt: "2026-06-25",
    buildCycleId: "cycle-mvp-week-1",
    relatedFiles: ["apps/web/src/features/waitlist"],
  },
  {
    id: "REQ-002",
    title: "Team Invite",
    status: "stakeholder_review",
    priority: "high",
    roadmapLane: "Now",
    milestoneId: "mvp",
    ownerId: "u-ha",
    assigneeId: "u-david",
    summary: "Admins can invite team members by email. Invite links expire after 14 days.",
    problem: "Team admins need a simple way to add members to a workspace.",
    expectedBehavior: "Admins can invite users by email. Invite links expire after 14 days.",
    acceptanceCriteria: [
      "Admin can invite a user by email.",
      "Non-admin cannot invite users.",
      "Invite email is sent.",
      "Invite link expires after 14 days.",
      "Expired invite shows an error message.",
    ],
    outOfScope: ["Bulk invite", "SSO invite", "Role-based invite customization"],
    technicalNotes: "Use existing email service and team permission model.",
    decisions: [
      { id: "d1", text: "Invite expiry: 14 days." },
      { id: "d2", text: "Bulk invite: out of scope for MVP." },
      { id: "d3", text: "Email provider: reuse existing email service." },
    ],
    relatedFiles: [
      "apps/web/src/features/team",
      "services/api/src/modules/invite",
      "services/api/src/modules/email",
    ],
    previewUrl: "https://staging.launchos.dev/team/invites",
    warning:
      "Spec says invite links expire after 14 days. Implementation uses 7 days in one test file.",
    gitSyncedAt: "2026-06-28",
    approvedAt: "2026-06-27",
    updatedAt: "2026-06-29",
    buildCycleId: "cycle-mvp-week-1",
  },
  {
    id: "REQ-003",
    title: "Product Asset Library",
    status: "in_development",
    priority: "high",
    roadmapLane: "Now",
    milestoneId: "mvp",
    ownerId: "u-linh",
    assigneeId: "u-david",
    summary: "Users can upload screenshots, logos, and documents for each product.",
    acceptanceCriteria: [
      "User can upload image or PDF.",
      "Asset appears in product asset list.",
      "User can add title and notes.",
      "User can delete an asset.",
    ],
    outOfScope: ["Large video uploads"],
    decisions: [{ id: "d1", text: "Limit uploads to 25MB per asset." }],
    updatedAt: "2026-06-29",
    buildCycleId: "cycle-mvp-week-1",
    relatedFiles: ["apps/web/src/features/assets"],
  },
  {
    id: "REQ-004",
    title: "Audience Import",
    status: "approved",
    priority: "high",
    roadmapLane: "Next",
    milestoneId: "beta",
    ownerId: "u-ha",
    summary: "Users can import audience contacts from CSV and use them for outreach campaigns.",
    acceptanceCriteria: [
      "User can upload CSV.",
      "System validates email column.",
      "Invalid rows are shown before import.",
      "Imported contacts appear in audience list.",
      "Duplicate emails are skipped.",
    ],
    outOfScope: ["Direct CRM sync"],
    decisions: [{ id: "d1", text: "CSV-only for first version." }],
    updatedAt: "2026-06-28",
    approvedAt: "2026-06-28",
  },
  {
    id: "REQ-005",
    title: "Public Partner Links",
    status: "review",
    priority: "medium",
    roadmapLane: "Later",
    milestoneId: "v1",
    ownerId: "u-anna",
    summary: "Users can add partner links to support SEO backlink exchange.",
    acceptanceCriteria: [],
    outOfScope: [],
    openQuestions: [
      "Should partner links require approval?",
      "Should links be nofollow or dofollow?",
      "Should we expose a public partner directory?",
    ],
    decisions: [],
    updatedAt: "2026-06-26",
  },
  {
    id: "REQ-006",
    title: "Billing Plan Limits",
    status: "draft",
    priority: "medium",
    roadmapLane: "Next",
    milestoneId: "beta",
    ownerId: "u-ha",
    summary: "Define free and paid plan limits for projects, AI credits, and team members.",
    acceptanceCriteria: [
      "Free plan has project limit.",
      "Team plan has higher project limit.",
      "AI credits are visible.",
      "Upgrade CTA appears when user reaches limit.",
    ],
    outOfScope: [],
    decisions: [],
    updatedAt: "2026-06-25",
  },
  {
    id: "REQ-007",
    title: "AI Weekly Project Summary",
    status: "request",
    priority: "low",
    roadmapLane: "Icebox",
    milestoneId: "v1",
    ownerId: "u-ha",
    summary: "Every Monday, the AI summarizes what changed in the project and what is blocked.",
    acceptanceCriteria: [],
    outOfScope: [],
    decisions: [],
    updatedAt: "2026-06-24",
  },
];

export const comments: Comment[] = [
  {
    id: "c1",
    specId: "REQ-002",
    authorId: "u-anna",
    text: "Can the success message be friendlier?",
    createdAt: "2026-06-28",
  },
  {
    id: "c2",
    specId: "REQ-002",
    authorId: "u-david",
    text: "Email service already exists, we can reuse Resend adapter.",
    createdAt: "2026-06-28",
  },
  {
    id: "c3",
    specId: "REQ-002",
    authorId: "u-ha",
    text: "Bulk invite is not needed for MVP.",
    createdAt: "2026-06-27",
  },
];

export const activities: Activity[] = [
  { id: "a1", text: "Anna approved REQ-001.", time: "2h ago", specId: "REQ-001" },
  { id: "a2", text: "David moved REQ-003 to In Development.", time: "3h ago", specId: "REQ-003" },
  { id: "a3", text: "AI generated context for REQ-002.", time: "4h ago", specId: "REQ-002" },
  { id: "a4", text: "Ha moved REQ-004 to Next.", time: "1d ago", specId: "REQ-004" },
  { id: "a5", text: "Linh commented on REQ-002 preview.", time: "1d ago", specId: "REQ-002" },
  {
    id: "a6",
    text: "SpecPilot detected a possible spec-code mismatch in REQ-002.",
    time: "1d ago",
    specId: "REQ-002",
  },
  { id: "a7", text: "Ha created REQ-007 from an idea.", time: "2d ago", specId: "REQ-007" },
  { id: "a8", text: "David linked a pull request to REQ-003.", time: "2d ago", specId: "REQ-003" },
];

export const initialState: DemoState = {
  mode: "team",
  currentProjectId: "launchos",
  specs,
  comments,
  activities,
  buildCycles,
  milestones,
};
